import { type NextPage } from "next";
import Head from "next/head";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import CreatePostWizard from "~/components/CreatePostWizard";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faWolfPackBattalion } from "@fortawesome/free-brands-svg-icons";
import PostView from "~/components/PostView";

type serverSidePropTypes = {
  sample: string
}
const Home: NextPage<serverSidePropTypes> = ({sample}: serverSidePropTypes) => {

  const { data: posts, isLoading, isError } = api.post.getAll.useQuery();

  const user = useUser();

  const buttonContent = !user?.isSignedIn ? (
    <SignInButton />
  ) : (
    <SignOutButton />
  );

  const fetchPosts = posts?.map((post) => <PostView postProp={post} />);

  if (isLoading) return <div>loading...</div>;
  if (isError) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className=" flex w-full flex-col items-center rounded-md border-x border-blue-500 md:max-w-2xl">
          <div className="flex w-full flex-col items-center gap-3 rounded-md border-b">
            {user?.isSignedIn && <CreatePostWizard />}

            <div className="fixed right-3 top-3 flex items-center gap-5 rounded-xl border border-white bg-white px-5 py-2">
              {user?.isSignedIn && (
                <>
                  <img
                    src={user.user?.profileImageUrl}
                    alt=""
                    className="h-12 w-12 rounded-full"
                  />
                  <div className="text-black">{user.user?.fullName}</div>
                </>
              )}
              <div className=" w-fit rounded-xl p-5 text-black">
                {buttonContent}
              </div>
            </div>
          </div>

          <div className="flex w-full flex-col items-center">{fetchPosts}</div>
        </div>

        {/* <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> checking what happen if it comment */}
      </main>
    </>
  );
};

export default Home;


export const getServerSideProps = async (context:any) => {
  return {
    props: {
      sample: 'hello world'
    }
  }

}
