import type { NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import CreatePostWizard from "~/components/CreatePostWizard";
import Loader from "~/components/Loader";
import Posts from "~/components/Posts";
import Link from "next/link";

type serverSidePropTypes = {
  sample: string
}
const Home: NextPage<serverSidePropTypes> = ({sample}: serverSidePropTypes) => {

  const user = useUser();
  const {isLoaded, isSignedIn, user: userData} = user;
  const buttonContent = !isSignedIn ? (
    <SignInButton />
  ) : (
    <SignOutButton />
  );

  if (!isLoaded) return <Loader size={50} />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className=" flex w-full flex-col items-center rounded-md border-x border-blue-500 md:max-w-2xl">
          <div className="flex w-full flex-col items-center gap-3 rounded-md border-b">
            <Link href={'/about'} >About</Link>
            {isSignedIn && <CreatePostWizard />}

            <div className="fixed right-3 top-3 flex items-center gap-5 rounded-xl border border-white bg-white px-5 py-2">
              {isSignedIn && (
                <>
                  <img
                    src={userData?.profileImageUrl}
                    alt=""
                    className="h-12 w-12 rounded-full"
                  />
                  <div className="text-black">{userData?.fullName}</div>
                </>
              )}
              <div className=" w-fit rounded-xl p-5 text-black">
                {buttonContent}
                {/* <SignInButton /> */}
              </div>
            </div>
          </div>

          <div className="flex w-full flex-col items-center"> <Posts /> </div>
        </div>

        {/* <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> checking what happen if it comment */}
      </main>
    </>
  );
};

export default Home;


export const getServerSideProps = async (context:any) => {
  return {
    props: {
      sample: 'hello world'
    }
  }
}
